repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.3.5
    hooks:
      - id: go-fmt
      - id: go-lint

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.28.1
    hooks:
      - id: golangci-lint
